[fr] Translations fixes
Laravel-Lang/attributes pull request #989
Opened 2024-09-26 07:43 UTC by max13fr

2024-09-26 18:32 UTC, caouecs requested changes

2024-09-26 18:32 UTC, caouecs commented on locales/fr/php.json
> +    "attributes.login": "login",
identifiant ?

2024-09-26 19:35 UTC, max13fr commented on locales/fr/php.json
> +    "attributes.login": "login",
good idea, fixed

2024-09-30 19:02 UTC, caouecs approved these changes

2024-09-30 19:54 UTC, andrey-helldar approved these changes
Merci

2024-09-30 19:54 UTC, merged